/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 20-Jul-2020 6:24:44 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

USE [UnitCostApp]
GO

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_SingleCostCatalog_CatalogType]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [SingleCostCatalog] DROP CONSTRAINT [FK_SingleCostCatalog_CatalogType]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_SingleCostCatalog_MeasureUnit]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [SingleCostCatalog] DROP CONSTRAINT [FK_SingleCostCatalog_MeasureUnit]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_SingleCostCatalog_SingleCostCatalog]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [SingleCostCatalog] DROP CONSTRAINT [FK_SingleCostCatalog_SingleCostCatalog]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CatalogType]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [CatalogType]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[MeasureUnit]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [MeasureUnit]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Project]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Project]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[SingleCostCatalog]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [SingleCostCatalog]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[User]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [User]
GO

/* Create Tables */

CREATE TABLE [CatalogType]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Name] varchar(50)
)
GO

CREATE TABLE [MeasureUnit]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Name] nvarchar(200),
	[Symbol] varchar(20)
)
GO

CREATE TABLE [Project]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Name] nvarchar(200),
	[Description] nvarchar(max)
)
GO

CREATE TABLE [SingleCostCatalog]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Key] nvarchar(20),
	[Name] nvarchar(200),
	[Description] nvarchar(max),
	[Cost] decimal(18,9),
	[UnitId] int,
	[ParentId] int,
	[IsComposed] bit,
	[CatalogTypeId] int
)
GO

CREATE TABLE [User]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Firstname] nvarchar(200),
	[Lastname] nvarchar(200),
	[Email] nvarchar(1000),
	[Password] nvarchar(1000),
	[Birthdate] date
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [CatalogType] 
 ADD CONSTRAINT [PK_CatalogType]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [MeasureUnit] 
 ADD CONSTRAINT [PK_MeasureUnit]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [Idx_Id] 
 ON [MeasureUnit] ([Id] ASC)
GO

ALTER TABLE [Project] 
 ADD CONSTRAINT [PK_Project]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [constraint1] 
 ON [Project] ([Id] ASC)
GO

ALTER TABLE [SingleCostCatalog] 
 ADD CONSTRAINT [PK_BasicCatalog]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [SingleCostCatalog] 
 ADD CONSTRAINT [Key_Unique] UNIQUE NONCLUSTERED ([Key] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_SingleCostCatalog_CatalogType] 
 ON [SingleCostCatalog] ([CatalogTypeId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_SingleCostCatalog_MeasureUnit] 
 ON [SingleCostCatalog] ([UnitId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_SingleCostCatalog_SingleCostCatalog] 
 ON [SingleCostCatalog] ([ParentId] ASC)
GO

CREATE UNIQUE NONCLUSTERED INDEX [Idx_Id] 
 ON [SingleCostCatalog] ([Id] ASC)
GO

ALTER TABLE [User] 
 ADD CONSTRAINT [PK_User]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [User] 
 ADD CONSTRAINT [Email_Unq] UNIQUE NONCLUSTERED ()
GO

CREATE UNIQUE NONCLUSTERED INDEX [Idx_Email] 
 ON [User] ([Email] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [SingleCostCatalog] ADD CONSTRAINT [FK_SingleCostCatalog_CatalogType]
	FOREIGN KEY ([CatalogTypeId]) REFERENCES [CatalogType] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [SingleCostCatalog] ADD CONSTRAINT [FK_SingleCostCatalog_MeasureUnit]
	FOREIGN KEY ([UnitId]) REFERENCES [MeasureUnit] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [SingleCostCatalog] ADD CONSTRAINT [FK_SingleCostCatalog_SingleCostCatalog]
	FOREIGN KEY ([ParentId]) REFERENCES [SingleCostCatalog] ([Id]) ON DELETE No Action ON UPDATE No Action
GO
